import type { Metadata } from "next";
import { Poppins } from "next/font/google";
import "./globals.css";
import Footer from "./Components/Footer/Footer";
import Navbar from "./Components/Navbar/Navbar";

const myfont = Poppins ({
  subsets: ["latin"],
  weight: ["400" , "700"]
});


export const metadata: Metadata = {
  title: "Ecommerce Desktop Website",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={myfont.className}
    
      >
        <Navbar/>
        {children}
        <Footer/>
      </body>
    </html>
  );
}
